services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    restart: unless-stopped

  mn-backend:
    container_name: mn-backend
    image: shawnjj/mn-backend:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mn-database
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: